on load:
    set {cb.const.prefix} to "&8[&6CityBuild&8]&r"
    set {cb.const.no-perm} to "&cYou do not have permission for this command."
    set {cb.const.default-spawn-cooldown-seconds} to 5
    set {cb.const.default-home-limit} to 1

    if {cb.debug.enabled} is not set:
        set {cb.debug.enabled} to false

    if {cb.spawn.cooldown-seconds} is not set:
        set {cb.spawn.cooldown-seconds} to {cb.const.default-spawn-cooldown-seconds}
