function cbColor(message: text) :: text:
    set {_message} to {_message}
    replace all "&" in {_message} with "§"
    return {_message}

function cbMessage(target: command sender, message: text):
    set {_prefix} to {cb.const.prefix}
    if {_prefix} is not set:
        set {_prefix} to "&8[&6CityBuild&8]&r"
    send cbColor("%{_prefix}% %{_message}%") to {_target}

function cbSuccess(target: command sender, message: text):
    set {_prefix} to {cb.const.prefix}
    if {_prefix} is not set:
        set {_prefix} to "&8[&6CityBuild&8]&r"
    send cbColor("%{_prefix}% &a%{_message}%") to {_target}

function cbError(target: command sender, message: text):
    set {_prefix} to {cb.const.prefix}
    if {_prefix} is not set:
        set {_prefix} to "&8[&6CityBuild&8]&r"
    send cbColor("%{_prefix}% &c%{_message}%") to {_target}

function cbDebug(message: text):
    if {cb.debug.enabled} is true:
        send cbColor("&8[&6CityBuild-Debug&8]&7 %{_message}%") to console
